### PR TITLE
Move util package to internal.util

### PR DESCRIPTION
**Pull request by enozcan**
The change is mentioned here:
hazelcast/hazelcast#15570

### CODE REVIEW

**Comment by leszko** [comment]
@enozcan Is it the same as: https://github.com/hazelcast/hazelcast-aws/pull/105?

**Comment by enozcan** [comment]
@leszko refers to the same issue with #105 but applies it to all necessary classes.

**Comment by leszko** [comment]
@enozcan Could you comment on #105 ? So that we close the other one and merge yours?

**Comment by mesutcelik** [comment]
verify

**Pull request merged**
