### PR TITLE
Moved StringUtil to internal package

### PR DESCRIPTION
**Pull request by mmedenjak**
Address compilation issue because of
https://github.com/hazelcast/hazelcast/pull/15570.

### CODE REVIEW

**Comment by mmedenjak** [comment]
I assumed the target release is 3.0, fix if necessary.

**Comment by leszko** [comment]
> I assumed the target release is 3.0, fix if necessary.

Did you mean `4.0`?

**Comment by mmedenjak** [comment]
@leszko there is no 4.0 milestone?
https://github.com/hazelcast/hazelcast-aws/milestones

**Comment by leszko** [comment]
@mmedenjak ahh, right, I though you meant the version of Hazelcast (Root). Anyway, thanks for the PR.

**Comment by leszko** [comment]
@hasancelik , could you please look at the Jenkins failures? I guess the `4.0-compatibility` branch should not fail with the hazelcast `master`. But it does. Could you check?

**Comment by hasancelik** [comment]
@leszko It is failing due to `util --> internal.util` change at hazelcast side. 
@mmedenjak could you apply same package name change to these failing class?
```
10:45:04 [ERROR] /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/aws/utility/RetryUtils.java:[22,25] error: package com.hazelcast.util does not exist
10:45:04 [ERROR] /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/aws/security/EC2RequestSigner.java:[22,25] error: package com.hazelcast.util does not exist
10:45:04 [ERROR] /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java:[25,25] error: package com.hazelcast.util does not exist
10:45:04 [ERROR] /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/aws/utility/RetryUtils.java:[56,26] error: cannot find symbol
10:45:04 [ERROR]   symbol:   variable ExceptionUtil
10:45:04   location: class RetryUtils
10:45:04 /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/aws/security/EC2RequestSigner.java:[146,15] error: cannot find symbol
10:45:04 [ERROR]   symbol:   variable QuickMath
10:45:04   location: class EC2RequestSigner
10:45:04 /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/aws/security/EC2RequestSigner.java:[186,26] error: cannot find symbol
10:45:04 [ERROR]   symbol:   variable QuickMath
10:45:04   location: class EC2RequestSigner
10:45:04 /home/jenkins/jenkins_slave/workspace/AWS-pr-builder/src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java:[76,18] error: cannot find symbol
```
Or I can close this PR and create one with other required changes?

**Comment by enozcan** [comment]
3 more classes use that package and hence have to be modified. #106 has handled them as well and can be merged instead of this.

**Pull request closed without merging**
