### PR TITLE
Updates README to use YAML instead of XML

### LINKED ISSUE #96: Update README.md to use YAML instead of XML

### PR DESCRIPTION
**Pull request by alparslanavci**
Fixes #96.

### CODE REVIEW

**Comment by hasancelik** [comment]
I think we should keep XML config as a separate section. Most of our users still use XML configuration. WDYT? @alparslanavci @leszko

**Comment by alparslanavci** [comment]
@hasancelik yes, we can keep them both, but I think it might be a good push to pass YAML config.

**Comment by hasancelik** [comment]
Afaik, IMDG core will continue to support XML for a long time so promoting YAML for Kubernetes service discovery is good idea but for AWS, I am not sure.

**Comment by nfrankel** [comment]
IMHO, XML is far superior to YAML, especially when the configuration is a bit large. That some want to use YAML is fine (...).

I'd suggest the documentation offers both, just as Spring does with Java and Kotlin support. Please see how it looks here: https://docs.spring.io/spring-framework/docs/5.2.x/spring-framework-reference/core.html#beans-factory-instantiation. There's one tab for Java, one for Kotlin so it doesn't impair readability.

**Comment by alparslanavci** [comment]
Ok, I added back the XML configuration samples.

**Pull request merged**
