### PR TITLE
Add read timeout for AWS endpoints

### PR DESCRIPTION
**Pull request by peterjot**
closes https://github.com/hazelcast/hazelcast-aws/issues/103

### CODE REVIEW

**Comment by alparslanavci** [comment]
verify

**Comment by alparslanavci** [comment]
@peterjot thanks for the contribution! Could you please rebase your branch with the current master and push again? There was an issue regarding checkstyle and we just committed the fix.

**Comment by Holmistr** [comment]
@peterjot :tada: Looks great! Regarding the CLA process, I'm sorry, I know it's tedious. We're working on having this much easier (with one click on GitHub), but we're not there yet. 

Can't wait for your signature :)

**Comment by peterjot** [comment]
Hey Jiri,

I already sent CLA to cla@hazelcast.com :)

śr., 19 lut 2020 o 10:44 Jiří Holuša <notifications@github.com> napisał(a):

**Comment by Holmistr** [comment]
@peterjot :tada: We have received the CLA! Merging this PR. You're now officially a Hazelcast contributor, thank you very much!

**Pull request merged**
