### PR TITLE
ZONE_AWARE support

### PR DESCRIPTION
**Pull request by emrahkocaman**
implement `discoverLocalMetadata` for zone awareness

### CODE REVIEW

**Comment by lazerion** [comment]
@emrahkocaman currently get below error on AWS
```
INFO: [10.0.2.245]:5701 [dev] [3.8.3] Hazelcast Shutdown is completed in 28 ms.
Exception in thread "main" java.lang.NoSuchMethodError: com.hazelcast.aws.AWSClient.getAvailabilityZone()Ljava/lang/String;
	at com.hazelcast.aws.AwsDiscoveryStrategy.discoverLocalMetadata(AwsDiscoveryStrategy.java:120)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverLocalMetadata(DefaultDiscoveryService.java:91)
	at com.hazelcast.instance.Node.mergeEnvironmentProvidedMemberMetadata(Node.java:498)
	at com.hazelcast.instance.Node.start(Node.java:383)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:132)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.core.server.StartServer.main(StartServer.java:46)
```

Used mvn command to create artifact:
```
mvn clean install -Dmaven.test.skip=true
```
since, tests do not pass on local-dev

**Comment by mesutcelik** [comment]
It looks like the new method `com.hazelcast.aws.AWSClient.getAvailabilityZone()` is not included in the jar uploaded to AWS. The other possiblity is that you are using hazelcast-all.jar which contains some old version of `hazelcast-aws` module

**Comment by lazerion** [comment]
@mesutcelik Thanks, the problem was using hazelcast-all.jar.

**Comment by emrahkocaman** [comment]
https://github.com/hazelcast/hazelcast-aws/pull/37 resolved aforementioned HTTP 401 error, (not related with this PR, introduced by #31 ).

**Pull request merged**
